package discount

import (
	"github.com/ottemo/foundation/env"
)

// Package global constants
const (
	ConstErrorModule = "discount"
	ConstErrorLevel  = env.ConstErrorLevelActor
)

// StructDiscount represents type to hold discount information generated by implementation of InterfaceDiscount
type StructAggregatedDiscount struct {
	Name   string
	Code   string
	Amount float64
	Object map[string]int
	Type   string
}
